apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: pelligent-in-tls
spec:
  secretName: pelligent-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pelligent.in
  dnsNames:
    - pelligent.in
    - www.pelligent.in