name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  GIT_SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t vzambare/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true vzambare/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-368004
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-south1-a
 
      - name: Build
        run: |-
          docker build -t vzambare/multi-client:latest -t vzambare/multi-client:$GIT_SHA -f ./client/Dockerfile ./client
          docker build -t vzambare/multi-server:latest -t vzambare/multi-server:$GIT_SHA -f ./server/Dockerfile ./server
          docker build -t vzambare/multi-worker:latest -t vzambare/multi-worker:$GIT_SHA -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push vzambare/multi-client:$GIT_SHA
          docker push vzambare/multi-server:$GIT_SHA
          docker push vzambare/multi-worker:$GIT_SHA

          docker push vzambare/multi-client:latest
          docker push vzambare/multi-server:latest
          docker push vzambare/multi-worker:latest
 
      - name: Apply
        run: |-
          kubectl apply -f k8s

          kubectl set image deployments/server-deployment server=vzambare/multi-server:$GIT_SHA
          kubectl set image deployments/client-deployment client=vzambare/multi-client:$GIT_SHA
          kubectl set image deployments/worker-deployment worker=vzambare/multi-worker:$GIT_SHA